Repository ChungangLions/lions-server, pull requests merged in 2025-08, with the labels that each got.

#3 User view 생성 및 swagger 작성
  project/accounts/migrations/0001_initial.py
  project/accounts/urls.py
  project/accounts/views.py
  project/config/urls.py
Labels: documentation, feature, modification

#4 close #1 - test: accounts/tests.py 작성 및 테스트
  project/accounts/serializers.py
  project/accounts/tests.py
  project/accounts/views.py
Labels: debug, enhancement, test, modification

#8 Dev/profile
  project/profiles/models.py
  project/profiles/serializers.py
Labels: feature

#25 Recommend model
  project/accounts/admin.py
  project/accounts/models.py
  project/accounts/serializers.py
  project/accounts/urls.py
  project/accounts/views.py
Labels: feature, modification

#37 Feat: 제안서 모델, 뷰 생성, Test: 로컬 테스트 통과
  project/accounts/serializers.py
  project/accounts/urls.py
  project/config/urls.py
  project/proposals/admin.py
  project/proposals/migrations/0001_initial.py
  project/proposals/models.py
  project/proposals/serializers.py
  project/proposals/urls.py
  project/proposals/views.py
Labels: debug, documentation, feature, test, modification

#38 Modify, Test: 제안서 모델 필드 수정
  project/proposals/admin.py
  project/proposals/migrations/0002_remove_proposal_max_redemptions_per_user_and_more.py
  project/proposals/models.py
  project/proposals/serializers.py
Labels: debug, test, modification

#39 Modify: 로그인 response로 id 필드 추가
  project/accounts/serializers.py
  project/accounts/views.py
Labels: documentation, modification

#43 Update proposal
  project/proposals/admin.py
  project/proposals/migrations/0003_remove_proposal_partnership_purpose.py
  project/proposals/migrations/0004_proposal_partnership_type.py
  project/proposals/models.py
  project/proposals/serializers.py
Labels: feature, test, modification

#47 modfiy: prompt 가중치 수정
  project/proposals/services/make_prompt.py
Labels: modification

#56 modify: 메뉴 로직 분리
  project/profiles/views.py
Labels: modification

#60 Request
  project/accounts/views.py
  project/profiles/serializers.py
Labels: debug, documentation, feature, modification

#61 modify: prompt 생성 함수 수정
  project/proposals/services/make_prompt.py
Labels: modification

#62 debug: prompt debug
  project/proposals/services/make_prompt.py
Labels: debug, modification

#64 제휴 유형, 제공 가능 서비스 모델 수정
  project/profiles/admin.py
  project/profiles/migrations/0009_remove_ownerprofile_available_service_and_more.py
  project/profiles/migrations/0010_remove_ownerprofile_partnership_goal_and_more.py
  project/profiles/models.py
  project/profiles/serializers.py
  project/profiles/views.py
Labels: modification

#65 Modify: proposals 모델을 수정 및 prompt 입력, 출력 예시 양식을 수정하였음.
  project/profiles/serializers.py
  project/proposals/admin.py
  project/proposals/migrations/0005_remove_proposal_apply_target_other_and_more.py
  project/proposals/models.py
  project/proposals/serializers.py
  project/proposals/services/make_prompt.py
  project/proposals/views.py
Labels: debug, documentation, feature, modification

#67 modify: migrations 변경
  project/profiles/migrations/0001_initial.py
  project/profiles/migrations/0002_remove_studentgroupprofile_partnership_record_and_more.py
  project/profiles/migrations/0003_studentprofile_name.py
  project/profiles/migrations/0004_alter_ownerprofile_off_peak_time_and_more.py
  project/profiles/migrations/0005_remove_ownerprofile_partnership_type.py
  project/profiles/migrations/0006_studentgroupprofile_department_and_more.py
  project/profiles/migrations/0007_ownerprofile_contact_studentgroupprofile_contact_and_more.py
  project/profiles/migrations/0008_alter_ownerprofile_available_service_and_more.py
  project/profiles/migrations/0009_remove_ownerprofile_available_service_and_more.py
  project/profiles/migrations/0010_remove_ownerprofile_partnership_goal_and_more.py
  project/profiles/migrations/0011_ownerprofile_business_type_other_and_more.py
Labels: modification

#72 Proposal api
  project/proposals/serializers.py
  project/proposals/views.py
Labels: feature
